spring.application.name=WeatherHub_API
spring.datasource.url=jdbc:postgresql://localhost:5432/weatherhub_bd
spring.datasource.username=SEU_USUARIO
spring.datasource.password=SUA_SENHA
server.port=8081


spring.jpa.properties.hibernate.jdbc.lab.non_contextual_creatiion= true